spring:
  application:
    name: ecommerce-multivendor
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate: ddl-auto=update
server:
  port : 5454